export const EMPLOYEE = {
  REQUEST: 'EMPLOYEE/REQUEST',
  RECIEVE: 'EMPLOYEE/RECIEVE',
  INVALIDATE: 'EMPLOYEE/INVALIDATE'
}

export const LOGIN = {
  ATTEMPT : 'LOGIN/ATTEMPT',
  FAILED : 'LOGIN/FAILED',
  SUCCESSFULL : 'LOGIN/SUCCESSFULL',
}
