export const EMPLOYEE = {
  REQUEST: 'EMPLOYEE/REQUEST',
  RECIEVE: 'EMPLOYEE/RECIEVE',
  INVALIDATE: 'EMPLOYEE/INVALIDATE'
}

export const AUTH = {
  SENDING_REQUEST: 'AUTH/SENDING_REQUEST',
  SET_ERROR_MESSAGE: 'AUTH/SET_ERROR_MESSAGE',
  SET_AUTH: 'AUTH/SET_AUTH',
}


